export enum Background {
  GET_RECORD_PATH_FROM_PROC_ARG = "getRecordPathFromProcArg",
  UPDATE_MENU_STATE = "updateMenuState",
  UPDATE_USI_POSITION = "updatePosition",
  STOP_USI = "stopUSI",
  SEND_USI_SET_OPTION = "sendUSISetOption",
  SHOW_OPEN_RECORD_DIALOG = "showOpenRecordDialog",
  OPEN_RECORD = "openRecord",
  SHOW_SAVE_RECORD_DIALOG = "showSaveRecordDialog",
  SAVE_RECORD = "saveRecord",
  SHOW_SELECT_FILE_DIALOG = "showSelectFileDialog",
  LOAD_APP_SETTING = "loadAppSetting",
  SAVE_APP_SETTING = "saveAppSetting",
  LOAD_RESEARCH_SETTING = "loadResearchSetting",
  SAVE_RESEARCH_SETTING = "saveResearchSetting",
  LOAD_GAME_SETTING = "loadGameSetting",
  SAVE_GAME_SETTING = "saveGameSetting",
  LOAD_USI_ENGINE_SETTING = "loadUSIEngineSetting",
  SAVE_USI_ENGINE_SETTING = "saveUSIEngineSetting",
  SHOW_SELECT_USI_ENGINE_DIALOG = "showSelectUSIEngineDialog",
  GET_USI_ENGINE_INFO = "getUSIEngineInfo",
  START_RESEARCH = "startResearch",
  END_RESEARCH = "endResearch",
  START_GAME = "startGame",
  END_GAME = "endGame",
}

export enum Renderer {
  SEND_ERROR = "sendError",
  MENU_EVENT = "menuEvent",
  USI_BEST_MOVE = "usiBestMove",
  USI_INFO = "usiInfo",
}
