export enum Background {
  GET_RECORD_PATH_FROM_PROC_ARG = "getRecordPathFromProcArg",
  UPDATE_MENU_STATE = "updateMenuState",
  SHOW_OPEN_RECORD_DIALOG = "showOpenRecordDialog",
  OPEN_RECORD = "openRecord",
  SHOW_SAVE_RECORD_DIALOG = "showSaveRecordDialog",
  SAVE_RECORD = "saveRecord",
  SHOW_SELECT_FILE_DIALOG = "showSelectFileDialog",
  LOAD_APP_SETTING = "loadAppSetting",
  SAVE_APP_SETTING = "saveAppSetting",
  LOAD_RESEARCH_SETTING = "loadResearchSetting",
  SAVE_RESEARCH_SETTING = "saveResearchSetting",
  LOAD_ANALYSIS_SETTING = "loadAnalysisSetting",
  SAVE_ANALYSIS_SETTING = "saveAnalysisSetting",
  LOAD_GAME_SETTING = "loadGameSetting",
  SAVE_GAME_SETTING = "saveGameSetting",
  LOAD_USI_ENGINE_SETTING = "loadUSIEngineSetting",
  SAVE_USI_ENGINE_SETTING = "saveUSIEngineSetting",
  SHOW_SELECT_USI_ENGINE_DIALOG = "showSelectUSIEngineDialog",
  GET_USI_ENGINE_INFO = "getUSIEngineInfo",
  SEND_USI_SET_OPTION = "sendUSISetOption",
  LAUNCH_USI = "usiLaunch",
  USI_GO = "usiGo",
  USI_GO_INFINITE = "usiGoInfinite",
  USI_STOP = "usiStop",
  USI_GAMEOVER = "usiGameover",
  USI_QUIT = "usiQuit",
}

export enum Renderer {
  SEND_ERROR = "sendError",
  MENU_EVENT = "menuEvent",
  USI_BEST_MOVE = "usiBestMove",
  USI_INFO = "usiInfo",
}
