export enum AppState {
  NORMAL = "normal",
  PASTE_DIALOG = "pasteDialog",
  POSITION_EDITING = "positionEditing",
  PIECE_SET_CHANGE_DIALOG = "pieceSetChangeDialog",
  EXPORT_POSITION_IMAGE_DIALOG = "exportBoardImageDialog",
  GAME_DIALOG = "gameDialog",
  GAME = "game",
  CSA_GAME_DIALOG = "csaGameDialog",
  CSA_GAME = "csaGame",
  RESEARCH = "research",
  RESEARCH_DIALOG = "researchDialog",
  ANALYSIS = "analysis",
  ANALYSIS_DIALOG = "analysisDialog",
  MATE_SEARCH = "mateSearch",
  MATE_SEARCH_DIALOG = "mateSearchDialog",
  USI_ENGINE_SETTING_DIALOG = "usiEngineSettingDialog",
  RECORD_FILE_HISTORY_DIALOG = "recordFileHistoryDialog",
  BATCH_CONVERSION_DIALOG = "batchConversionDialog",
  LAUNCH_USI_ENGINE_DIALOG = "launchUsiEngineDialog",
  CONNECT_TO_CSA_SERVER_DIALOG = "connectToCsaServerDialog",
  LOAD_REMOTE_FILE_DIALOG = "loadRemoteFileDialog",
}
