export enum AppState {
  NORMAL = "normal",
  PASTE_DIALOG = "pasteDialog",
  POSITION_EDITING = "positionEditing",
  GAME_DIALOG = "gameDialog",
  GAME = "game",
  CSA_GAME_DIALOG = "csaGameDialog",
  CSA_GAME = "csaGame",
  RESEARCH = "research",
  RESEARCH_DIALOG = "researchDialog",
  ANALYSIS = "analysis",
  ANALYSIS_DIALOG = "analysisDialog",
  USI_ENGINE_SETTING_DIALOG = "usiEngineSettingDialog",
  TEMPORARY = "temporary",
}
