import {
  exportCSA,
  importCSA,
  Move,
  Position,
  Record,
  RecordMetadataKey,
  SpecialMove,
} from "@/common/shogi";

describe("shogi/csa", () => {
  it("import/standard", () => {
    const data = `
' CSA形式棋譜ファイル Generated by Electron Shogi
V2.2
N+Electron John
N-Mr.Vue
$EVENT:TypeScript Festival
P1-KY-KE-GI-KI-OU-KI-GI-KE-KY
P2 * -HI *  *  *  *  * -KA * 
P3-FU-FU-FU-FU-FU-FU-FU-FU-FU
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  *  *  *  * 
P7+FU+FU+FU+FU+FU+FU+FU+FU+FU
P8 * +KA *  *  *  *  * +HI * 
P9+KY+KE+GI+KI+OU+KI+GI+KE+KY
P+
P-
+
+7776FU
T0
'無視すべきコメント
'*初手に対するコメント
'*初手に対するコメント2
'** 読み筋と評価値
-3334FU
T0
+8822UM
T10
-3122GI
T20
+0045KA
T30
%TORYO
'*特殊な手に対するコメント
T40
`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.BLACK_NAME)
    ).toBe("Electron John");
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.WHITE_NAME)
    ).toBe("Mr.Vue");
    expect(record.initialPosition.sfen).toBe(
      "lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1"
    );
    expect(record.current.number).toBe(0);
    expect(record.current.move).toBe(SpecialMove.START);
    record.goto(1);
    expect((record.current.move as Move).getDisplayText()).toBe("☗７六歩(77)");
    expect(record.current.comment).toBe(
      "初手に対するコメント\n初手に対するコメント2\n* 読み筋と評価値\n"
    );
    record.goto(2);
    expect((record.current.move as Move).getDisplayText()).toBe("☖３四歩(33)");
    record.goto(3);
    expect((record.current.move as Move).getDisplayText()).toBe(
      "☗２二角成(88)"
    );
    expect(record.current.elapsedMs).toBe(10000);
    record.goto(4);
    expect((record.current.move as Move).getDisplayText()).toBe("☖２二銀(31)");
    expect(record.current.elapsedMs).toBe(20000);
    record.goto(5);
    expect((record.current.move as Move).getDisplayText()).toBe("☗４五角打");
    expect(record.current.elapsedMs).toBe(30000);
    record.goto(6);
    expect(record.current.move).toBe(SpecialMove.RESIGN);
    expect(record.current.comment).toBe("特殊な手に対するコメント\n");
    expect(record.current.elapsedMs).toBe(40000);
  });

  it("import/standard2", () => {
    const data = `'----------棋譜ファイルの例"example.csa"-----------------
'バージョン
V2.2
'対局者名
N+NAKAHARA
N-YONENAGA
'棋譜情報
'棋戦名
$EVENT:13th World Computer Shogi Championship
'対局場所
$SITE:KAZUSA ARC
'開始日時
$START_TIME:2003/05/03 10:30:00
'終了日時
$END_TIME:2003/05/03 11:11:05
'持ち時間:25分、切れ負け
$TIME_LIMIT:00:25+00
'戦型:矢倉
$OPENING:YAGURA
'平手の局面
P1-KY-KE-GI-KI-OU-KI-GI-KE-KY
P2 * -HI *  *  *  *  * -KA * 
P3-FU-FU-FU-FU-FU-FU-FU-FU-FU
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  *  *  *  * 
P7+FU+FU+FU+FU+FU+FU+FU+FU+FU
P8 * +KA *  *  *  *  * +HI * 
P9+KY+KE+GI+KI+OU+KI+GI+KE+KY
'先手番
+
'指し手と消費時間
+2726FU
T12
-3334FU
T6
%CHUDAN
'---------------------------------------------------------`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    expect(record.initialPosition.sfen).toBe(
      "lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1"
    );
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.BLACK_NAME)
    ).toBe("NAKAHARA");
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.WHITE_NAME)
    ).toBe("YONENAGA");
    expect(record.metadata.getStandardMetadata(RecordMetadataKey.TITLE)).toBe(
      "13th World Computer Shogi Championship"
    );
    expect(record.metadata.getStandardMetadata(RecordMetadataKey.PLACE)).toBe(
      "KAZUSA ARC"
    );
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.START_DATETIME)
    ).toBe("2003/05/03 10:30:00");
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.END_DATETIME)
    ).toBe("2003/05/03 11:11:05");
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.TIME_LIMIT)
    ).toBe("00:25+00");
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.STRATEGY)
    ).toBe("YAGURA");
    expect(record.moves).toHaveLength(4);
    expect(record.moves[0].move).toBe(SpecialMove.START);
    expect((record.moves[1].move as Move).usi).toBe("2g2f");
    expect((record.moves[2].move as Move).usi).toBe("3c3d");
    expect(record.moves[3].move).toBe(SpecialMove.INTERRUPT);
  });

  it("import/illegal_move", () => {
    const data = `V2.2
PI
+
+7776FU
-3334FU
%ILLEGAL_MOVE
`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    record.goto(3);
    expect(record.current.move).toBe(SpecialMove.FOUL_LOSE);
  });

  it("import/jishogi", () => {
    const data = `V2.2
PI
+
+7776FU
-3334FU
%JISHOGI
`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    record.goto(3);
    expect(record.current.move).toBe(SpecialMove.IMPASS);
  });

  it("import/kachi", () => {
    const data = `V2.2
PI
+
+7776FU
-3334FU
%KACHI
`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    record.goto(3);
    expect(record.current.move).toBe(SpecialMove.ENTERING_OF_KING);
  });

  it("import/custom-position", () => {
    const data = `
V2.2
P1 *  *  *  *  *  *  * -KE * 
P2 *  *  *  *  *  * -KI-OU * 
P3 *  *  *  *  *  * -KI-FU+KE
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  * -KA * +FU
P7 *  *  *  *  *  *  *  *  * 
P8 *  *  *  *  *  *  *  *  * 
P9 *  *  *  *  *  *  *  *  * 
P+00HI00HI00KI00KI
P-00AL
+
+1321NK,T0
-2221OU,T0
+0013KE,T0
-2122OU,T0
+0012KI,T0
-2212OU,T0
+0011HI,T0
-1211OU,T0
+0021KI,T0
-1112OU,T0
+0011HI,T0
%TSUMI,T0
`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    expect(record.initialPosition.sfen).toBe(
      "7n1/6gk1/6gpN/9/9/6b1P/9/9/9 b 2R2Gb4s2n4l16p 1"
    );
    expect(record.current.number).toBe(0);
    expect(record.current.move).toBe(SpecialMove.START);
    record.goto(1);
    expect((record.current.move as Move).getDisplayText()).toBe(
      "☗２一桂成(13)"
    );
    record.goto(10);
    expect((record.current.move as Move).getDisplayText()).toBe("☖１二玉(11)");
    record.goto(11);
    expect((record.current.move as Move).getDisplayText()).toBe("☗１一飛打");
    record.goto(12);
    expect(record.current.move).toBe(SpecialMove.MATE);
  });

  it("import/wcsc32", () => {
    // http://www2.computer-shogi.org/kifu/kifu.html より
    const data = `V2.2
N+二番絞り
N-dlshogi with HEROZ
$START_TIME:2022/05/05 16:11:27
PI
+
+2726FU
T41
-8384FU
T0
+2625FU
T14
-8485FU
T0
+7776FU
T62
-4132KI
T0
+8877KA
T2
-3334FU
T0
+7988GI
T11
-2277UM
T0
+8877GI
T3
-3122GI
T0
+6978KI
T28
-2233GI
T0
+3938GI
T23
-7374FU
T0
+3736FU
T72
-7162GI
T0
+4746FU
T62
-5142OU
T0
+3847GI
T42
-1314FU
T0
+1716FU
T53
-9394FU
T0
+9796FU
T3
-8173KE
T0
+5968OU
T10
-6364FU
T0
+2937KE
T5
-6263GI
T0
+4948KI
T7
-6162KI
T0
+4756GI
T30
-8281HI
T0
+6766FU
T5
-6354GI
T0
+2829HI
T4
-4252OU
T0
+6879OU
T12
-4344FU
T0
+7988OU
T39
-8141HI
T0
+2928HI
T113
-4181HI
T0
+4858KI
T20
-6465FU
T17
+6665FU
T3
-7365KE
T15
+7766GI
T3
-0064FU
T6
+5868KI
T3
-8586FU
T4
+8786FU
T3
-8186HI
T4
+0087FU
T3
-8681HI
T4
+4645FU
T3
-4445FU
T4
+3745KE
T30
-3344GI
T0
+2524FU
T3
-2324FU
T4
+2824HI
T3
-0046KA
T96
+3635FU
T3
-0023FU
T103
+2434HI
T3
-5443GI
T3
+3432RY
T25
-4332GI
T0
+0022FU
T13
-0086FU
T0
+8786FU
T3
-0085FU
T3
+8685FU
T19
-4619UM
T0
+2221TO
T3
-0086KY
T28
+0087KI
T12
-8687KY
T25
+7887KI
T8
-0048HI
T0
+0069FU
T21
-1946UM
T0
+0078KE
T29
-8121HI
T0
+0034KY
T47
-0033FU
T0
+4533NK
T3
-4433GI
T35
+3433NY
T32
-3233GI
T0
+0025KA
T7
-5242OU
T0
+0044FU
T8
-3344GI
T0
+0043GI
T34
-4231OU
T0
+0045FU
T12
-4433GI
T0
+3534FU
T10
-3322GI
T0
+6665GI
T7
-4624UM
T0
+0033KE
T6
-0051KI
T0
+3321NK
T47
-3121OU
T0
+0026FU
T28
-6465FU
T2
+0081HI
T11
-0061KY
T13
+8191RY
T1
-0064KE
T12
+9192RY
T1
-0072KE
T96
+0063KY
T31
-0032FU
T0
+6362NY
T1
-5162KI
T4
+9272RY
T10
-6272KI
T28
+4332NG
T1
-2132OU
T25
+0044KE
T1
-3221OU
T12
+0032KI
T1
-2112OU
T4
+3222KI
T1
-1222OU
T4
+0033GI
T1
-2213OU
T4
+3324NG
T1
-1324OU
T41
+3433TO
T1
-2435OU
T5
+0037KA
T1
-6456KE
T3
+3748KA
T1
-5648NK
T3
+0036HI
T1
-3545OU
T3
+0046FU
T1
-4554OU
T3
+2561UM
T1
-0062KI
T3
+6172UM
T1
-6272KI
T24
+3343TO
T1
-0086FU
T12
+3633RY
T1
-0055KA
T8
+0077KY
T1
-8687TO
T23
+8887OU
T1
-0061KY
T84
+4353TO
T1
-5464OU
T3
+0054KI
T9
-6473OU
T0
+5455KI
T5
-7382OU
T0
+0045KA
T5
-7271KI
T0
+7886KE
T5
-0049KA
T1
+5363TO
T42
-8291OU
T0
+6878KI
T15
-0066KI
T6
+8788OU
T26
-0067GI
T0
+8897OU
T32
-6778GI
T4
+4578KA
T2
-0079HI
T7
%TORYO
T16
`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.BLACK_NAME)
    ).toBe("二番絞り");
    expect(
      record.metadata.getStandardMetadata(RecordMetadataKey.WHITE_NAME)
    ).toBe("dlshogi with HEROZ");
    expect(record.initialPosition.sfen).toBe(
      "lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1"
    );
    record.goto(177);
    expect(record.current.move).toBe(SpecialMove.RESIGN);
    expect(record.position.sfen).toBe(
      "k1gl4l/9/3+P2+Rp1/p1p2N2p/1P1pG4/PNPg1P1PP/K1L1P4/2B2+n3/LNrP1b3 b S4Pg3s 1"
    );
  });

  it("import/handicap", () => {
    const data = `V2.2
PI82HI
-
`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    expect(record.initialPosition.sfen).toBe(
      "lnsgkgsnl/7b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL w - 1"
    );
  });

  it("import/multi-records", () => {
    const data = `V2.2
PI
+
+2726FU
-3334FU
%CHUDAN
/
V2.2
PI
+
+7776FU
-8384FU
+5756FU
%CHUDAN`;
    const record = importCSA(data) as Record;
    expect(record).toBeInstanceOf(Record);
    expect(record.moves).toHaveLength(4);
  });

  it("export/standard", () => {
    const record = new Record();
    record.metadata.setStandardMetadata(
      RecordMetadataKey.BLACK_NAME,
      "Electron John"
    );
    record.metadata.setStandardMetadata(RecordMetadataKey.WHITE_NAME, "Mr.Vue");
    record.metadata.setStandardMetadata(
      RecordMetadataKey.TITLE,
      "TypeScript Festival"
    );
    record.append(record.position.createMoveByUSI("7g7f") as Move);
    record.append(record.position.createMoveByUSI("3c3d") as Move);
    record.current.comment = "2手目へのコメント\n2手目へのコメント2\n";
    record.append(record.position.createMoveByUSI("8h2b+") as Move);
    record.append(record.position.createMoveByUSI("3a2b") as Move);
    record.current.setElapsedMs(12345); // 12.345 seconds
    record.append(record.position.createMoveByUSI("B*4e") as Move);
    record.current.setElapsedMs(34567); // 34.567 seconds
    record.append(SpecialMove.RESIGN);
    record.current.setElapsedMs(56789); // 56.789 seconds
    expect(exportCSA(record, {}))
      .toBe(`' CSA形式棋譜ファイル Generated by Electron Shogi
V2.2
N+Electron John
N-Mr.Vue
$EVENT:TypeScript Festival
P1-KY-KE-GI-KI-OU-KI-GI-KE-KY
P2 * -HI *  *  *  *  * -KA * 
P3-FU-FU-FU-FU-FU-FU-FU-FU-FU
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  *  *  *  * 
P7+FU+FU+FU+FU+FU+FU+FU+FU+FU
P8 * +KA *  *  *  *  * +HI * 
P9+KY+KE+GI+KI+OU+KI+GI+KE+KY
P+
P-
+
+7776FU
T0
-3334FU
T0
'*2手目へのコメント
'*2手目へのコメント2
+8822UM
T0
-3122GI
T12
+0045KA
T34
%TORYO
T56
`);
  });

  it("export/custom-position", () => {
    const position = Position.newBySFEN(
      "7n1/6gk1/6gpN/9/9/6b1P/9/9/9 b 2R2Gb4s2n4l16p 1"
    ) as Position;
    const record = new Record(position) as Record;
    record.append(record.position.createMoveByUSI("1c2a+") as Move);
    record.append(record.position.createMoveByUSI("2b2a") as Move);
    expect(exportCSA(record, {}))
      .toBe(`' CSA形式棋譜ファイル Generated by Electron Shogi
V2.2
P1 *  *  *  *  *  *  * -KE * 
P2 *  *  *  *  *  * -KI-OU * 
P3 *  *  *  *  *  * -KI-FU+KE
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  * -KA * +FU
P7 *  *  *  *  *  *  *  *  * 
P8 *  *  *  *  *  *  *  *  * 
P9 *  *  *  *  *  *  *  *  * 
P+00KI00KI00HI00HI
P-00FU00FU00FU00FU00FU00FU00FU00FU00FU00FU00FU00FU00FU00FU00FU00FU00KY00KY00KY00KY00KE00KE00GI00GI00GI00GI00KA
+
+1321NK
T0
-2221OU
T0
`);
  });

  it("export/time_up", () => {
    const record = new Record();
    record.append(record.position.createMoveByUSI("7g7f") as Move);
    record.append(record.position.createMoveByUSI("3c3d") as Move);
    record.append(SpecialMove.TIMEOUT);
    expect(exportCSA(record, {}))
      .toBe(`' CSA形式棋譜ファイル Generated by Electron Shogi
V2.2
P1-KY-KE-GI-KI-OU-KI-GI-KE-KY
P2 * -HI *  *  *  *  * -KA * 
P3-FU-FU-FU-FU-FU-FU-FU-FU-FU
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  *  *  *  * 
P7+FU+FU+FU+FU+FU+FU+FU+FU+FU
P8 * +KA *  *  *  *  * +HI * 
P9+KY+KE+GI+KI+OU+KI+GI+KE+KY
P+
P-
+
+7776FU
T0
-3334FU
T0
%TIME_UP
T0
`);
  });

  it("export/illegal_move", () => {
    const record = new Record();
    record.append(record.position.createMoveByUSI("7g7f") as Move);
    record.append(record.position.createMoveByUSI("3c3d") as Move);
    record.append(SpecialMove.FOUL_LOSE);
    expect(exportCSA(record, {}))
      .toBe(`' CSA形式棋譜ファイル Generated by Electron Shogi
V2.2
P1-KY-KE-GI-KI-OU-KI-GI-KE-KY
P2 * -HI *  *  *  *  * -KA * 
P3-FU-FU-FU-FU-FU-FU-FU-FU-FU
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  *  *  *  * 
P7+FU+FU+FU+FU+FU+FU+FU+FU+FU
P8 * +KA *  *  *  *  * +HI * 
P9+KY+KE+GI+KI+OU+KI+GI+KE+KY
P+
P-
+
+7776FU
T0
-3334FU
T0
%ILLEGAL_MOVE
T0
`);
  });

  it("export/jishogi", () => {
    const record = new Record();
    record.append(record.position.createMoveByUSI("7g7f") as Move);
    record.append(record.position.createMoveByUSI("3c3d") as Move);
    record.append(SpecialMove.IMPASS);
    expect(exportCSA(record, {}))
      .toBe(`' CSA形式棋譜ファイル Generated by Electron Shogi
V2.2
P1-KY-KE-GI-KI-OU-KI-GI-KE-KY
P2 * -HI *  *  *  *  * -KA * 
P3-FU-FU-FU-FU-FU-FU-FU-FU-FU
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  *  *  *  * 
P7+FU+FU+FU+FU+FU+FU+FU+FU+FU
P8 * +KA *  *  *  *  * +HI * 
P9+KY+KE+GI+KI+OU+KI+GI+KE+KY
P+
P-
+
+7776FU
T0
-3334FU
T0
%JISHOGI
T0
`);
  });

  it("export/kachi", () => {
    const record = new Record();
    record.append(record.position.createMoveByUSI("7g7f") as Move);
    record.append(record.position.createMoveByUSI("3c3d") as Move);
    record.append(SpecialMove.ENTERING_OF_KING);
    expect(exportCSA(record, {}))
      .toBe(`' CSA形式棋譜ファイル Generated by Electron Shogi
V2.2
P1-KY-KE-GI-KI-OU-KI-GI-KE-KY
P2 * -HI *  *  *  *  * -KA * 
P3-FU-FU-FU-FU-FU-FU-FU-FU-FU
P4 *  *  *  *  *  *  *  *  * 
P5 *  *  *  *  *  *  *  *  * 
P6 *  *  *  *  *  *  *  *  * 
P7+FU+FU+FU+FU+FU+FU+FU+FU+FU
P8 * +KA *  *  *  *  * +HI * 
P9+KY+KE+GI+KI+OU+KI+GI+KE+KY
P+
P-
+
+7776FU
T0
-3334FU
T0
%KACHI
T0
`);
  });
});
